config/routes.rb
Rails.application.routes.draw do
  get 'properties/index'
  get 'properties/show/:id', to: "properties#show", as: "property_show"
  post "properties/update/:id", to: "properties#update", as: "property_update"
  post 'properties/create', to: "properties#create", as: "property_create"
  post 'comments/create', to: "comments#create", as: "comment_create"
  delete 'properties/delete/:id', to: "properties#destroy", as: "property_destroy"
  delete 'comments/delete/:id', to: "comments#delete", as: "comment_destroy"
  devise_for :users
  root 'static_pages#index'

  #owners
  post 'properties/new_owner', to: "owners#create", as: "owner_create"
  post 'properties/owner/:id', to: "owners#update", as: "owner_update"
  get 'properties/owner/:id', to: "owners#edit" , as: "owner_edit"
  get 'properties/owner_info/:id', to: "owners#show", as: "owner_show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :property
  belongs_to :user
end

app/models/owner.rb
class Owner < ApplicationRecord
    has_one :property
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :properties
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :last_name, :username,:email, :password)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :last_name, :username, :email, :password, :current_password)}
         end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
        @comment=Comment.new
    end
    def create
        if current_user
            @comment= current_user.comments.build(comments_params)
            if @comment.save
                flash[:notice]="Comentario agregado correctamente"
                redirect_to property_show_path(@comment.property_id)
            else
                flash[:notice]="Error, no se pudo agregar el comentario"
                redirect_to property_show_path(@comment.property_id)
            end 
        else
            flash[:notice]="Debes iniciar sesión para comentar" 
            redirect_to new_user_session_path
        end
    end
    def delete
        @comment = Comment.find(params[:id])
        if @comment.destroy
            flash[:notice]="Comentario eliminado"
            redirect_to property_show_path(@comment.property_id)
        end
    end 

    private 
    def comments_params
        params.require(:comment).permit(:property_id, :content, :rating, :evidence)
    end 

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

    def show 
        @owner = Owner.find(params[:id])
        @owner_calif = ((@owner.atention + @owner.respuesta + @owner.amabilidad)/3).round(2)
    end

    def create 
        @owner= Owner.new(owner_params)
        if @owner.save
        flash[:success] = "Se creó la propiedad correctamente"
        redirect_to properties_index_path
        else
        flash[:danger] = "hubó un error al crear la propiedad"
        redirect_to properties_index_path
        end
    end
    def edit 
        @owner = Owner.find(params[:id])
    end

    def update
        @owner = Owner.find(params[:id])
        if @owner.update(owner_params)
          flash[:success] = "Se creó la propiedad correctamente"
          redirect_to properties_index_path
        else
          flash[:danger] = "hubó un error al crear la propiedad"
          redirect_to properties_index_path
        end
    end

    private 
    def owner_params
        params.require(:owner).permit(:name, :atention, :respuesta, :amabilidad)
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    unless user_signed_in?
      redirect_to root_path
    end
  end

  def show
    @property = Property.find(params[:id])
    @evidences = []    
    if @property.evidence
      @evidences = @property.evidence.split(',')
    end
  end

  def new
    @property = Property.new
  end

  def create
    @owner = Owner.create(name: " ")
    @property= current_user.properties.build(property_params)
    @property.owner_id = @owner.id
    if @property.save
      flash[:success] = "Se creó la propiedad correctamente"
      redirect_to owner_edit_path(@property.owner_id)
    else
      flash[:danger] = "hubó un error al crear la propiedad"
      redirect_to properties_index_path
    end
  end

  def destroy
    @property = Property.find(params[:id])
    if @property.destroy
      flash[:success] = "Se borró la propiedad exitosamente"
      redirect_to properties_index_path
    else
      flash[:danger] = "Hubó un problema al borrar la propiedad"
      redirect_to properties_index_path
    end

    
  end

  def update
    @property = Property.find(params[:id])
    if @property.update(property_params)
      flash[:success] = "Se actuaizo la propiedad correctamente"
      redirect_to properties_index_path
    else
      flash[:danger] = "Hubó un error al editar la propiedad"
      redirect_to properties_index_path
    end
  end

  private

  def property_params
    params.require(:property).permit(:name, :description, :security, :noise, :cleaning, :image, :address, :rating, :evidence)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    if Property.any?
      @properties2 = Property.all.shuffle
      if params[:query].present?
         @properties =  Property.where("address LIKE ?", "%#{params[:query]}%")
      else
        @properties = Property.all.shuffle
      end
    end
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => e
        if get?
          raise e
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end
  
    self.responder = Responder
    respond_to :html, :turbo_stream
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>House</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

  <%= javascript_importmap_tags %>
</head>

<body>
  <% if flash.any? %>
  <% flash.each do |type, msg| %>
  <!-- <div data-aos="fade-up" class="alert alert-<%#= type %> alert-dismissible fade show fixed-top mt-3" role="alert"> -->
    <div data-aos="fade-up" class="alert alert-dark alert-dismissible fade show fixed-top mt-3" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <% end %>
  <% end %>
  <%= render "partials/navbar" %>
  <%= yield %>
</body>

</head>
</html>

app/views/owners/edit.html.erb
<section id="property-owner" class="container-fluid">
    <div class="row">
        <div class="col-10 col-sm-9 col-md-8 col-lg-7 col-xl-6 mx-auto">
            <h5 class="text-center display-3 mt-3">Dueño de la propiedad</h5>
            <div class="form-owner">
                <%= form_for :owner, url: owner_update_path(@owner.id), class: "border bg-light shadow my-5 rounded p-5" do |f| %>
                <div class="form-group">
                    <!-- Quitar nombre y poner reseña del propietario y agregar una caja de comentarios que cualquiera puede agregar comentarios -->
                    <%= f.label "Nombre del propietario", class: "form-label" %><br/>
                    <%= f.text_field :name, class: "form-control", required: true %>
                </div>
                <div class="form-group">
                    <%= f.label "Atención", class: "form-label" %><br/>
                    <%= f.select :atention, (1..5).to_a, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.label "Respuesta", class: "form-label" %><br/>
                    <%= f.select :respuesta, (1..5).to_a, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.label "Amabilidad", class: "form-label" %><br/>
                    <%= f.select :amabilidad, (1..5).to_a, class: "form-control" %>
                </div>

                <div class="form-group">
                    <%= f.submit "Agregar Propiedad", class: "btn btn-blue mt-3" %>
                </div>
                <% end %>
            </div>

        </div>
    </div>
</section>

app/views/owners/show.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-10 col-sm-9 col-md-8 col-lg-7 col-xl-6 mx-auto my-5">
            <h1 class="text-center display-3">Detalles del dueño</h1>
            <%= link_to "Ver propiedades", properties_index_path, class: "btn btn-blue mb-3" %>
            <div class="rounded shadow radius p-3 m-1">                
                <p class="text-capitalize">Nombre: <%= Faker::Internet.unique.user_name %></p>
                <p>Atención: <%= @owner.atention%></p>
                <p>Respuesta: <%= @owner.respuesta%></p>
                <p>Amabilidad: <%= @owner.amabilidad%></p>
                <p>Calificación: <%= @owner_calif%></p>
            </div>
        </div>
    </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light"style="background-color: rgba(23, 26, 29, 0.8);">
  <div class="container-fluid">
    <%= link_to root_path, class:"navbar-brand" do %>
      <i class="bi bi-house text-white fs-2"></i>
     <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%if current_user%>
          <%=link_to "Propiedades", properties_index_path, class:"nav-link"%>
          <%end%>
        </li>
      </ul>
    </div>
  </div>
  <div class="w-50 d-flex justify-content-end">
    <% if current_user %>
    <div class="nav-item">
    <%= link_to edit_user_registration_path, class:"navbar-brand d-flex" do %>
      <i class="bi bi-person me-2 text-white"></i>
      <p class="text-white">Hola <%= current_user.username %></p>
     <% end %>

    </div>
    <div class="nav-item">
      <%= button_to "Sign out", destroy_user_session_path, method: :delete , class:"btn btn-danger me-2"%>
    </div>
    <%else%>
    <div class="nav-item">
      <%= link_to "Sign Up", new_user_registration_path, class:"nav-link btn btn-purple me-2" %>
    </div>
    <div class="nav-item me-2">
      <%= link_to "Login", new_user_session_path, class:'nav-link btn btn-blue'%>
    </div>
    <%end%>
  </div>
</nav>

app/views/properties/index.html.erb
<section id="properties-index" class="container-fluid">
	<div class="row">
		<div class="col-10 mx-auto">
			<h1>Tus propiedades</h1>
			<p>Lista de propiedas que has evaluado</p>
			<!-- Button trigger modal -->
			<button type="button" class="btn btn-blue my-1" data-bs-toggle="modal" data-bs-target="#exampleModal">
				<i class="bi bi-plus-circle"></i> Agregar propiedad
			</button> 

			<!-- Modal -->
			<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<h5 class="modal-title" id="exampleModalLabel">Propiedad Nueva</h5>
							<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
						</div>
						<div class="modal-body">
							<%= form_for :property, url: property_create_path do |f| %>
								<!-- El modelo reseña solo se podrá publicar si el comprobante de domicilio corresponde con el de la propiedad -->
							<div class="form-group">
								<%= f.label "Dirección" %><br/>
								<%= f.text_field :address, class: "form-control", required: true %>
								
							</div>
							
							<div class="form-group">
								<%= f.label "Calificación que le das" %><br/>
								<%= f.select :rating, (1..5).to_a %>
							</div>
							<div class="form-group">
								<%= f.label "¿Por qué le das esta Calificación?" %><br/>
								<%= f.text_field :description, class: "form-control", required: true %>
							</div>
							<div class="form-group">
								<%= f.label "Url de la imagen" %><br/>
								<%= f.text_field :image, class: "form-control", required: true %>
							</div>
							<div class="form-group">
								<%= f.label "Evidencias" %><br/>
								<%= f.text_area :evidence, class: "form-control", required: true %>
							</div>
							<div class="form-group">								
								<%= f.submit "Agregar Propiedad", class: "btn btn-primary mt-3" %>
							</div>

							<% end %>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
						</div>
					</div>
				</div>
			</div>
			<div class="container-fluid mt-5">
				<div class="row">
					<% unless current_user.properties.nil? %>
					<% current_user.properties.each do | property| %>
					<div class="col-12 col-sm-6 col-md-4 col-xl-3">
						<div class="card">
							<img src="<%= property.image %>" class="card-img-top" alt="">
							<div class="card-body">
								<h5><%= property.name %></h5>
								<p class="card-text"><p><%= property.description %></p>
								<p class="card-text"><p><%= property.address %></p>
								<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

								<span class="fa fa-star checked"></span>
								<span class="fa fa-star checked"></span>
								<span class="fa fa-star checked"></span>
								<span class="fa fa-star"></span>
								<span class="fa fa-star"></span>
								<p class="card-text">Tú calificación: <%= property.rating %></p>
								<p class="text-capitalize">Dueño: <%= link_to Faker::Internet.unique.user_name, owner_show_path(property.owner_id) %></p>
								<p>Calificación del dueño: <%=((Owner.find(property.owner_id).atention + Owner.find(property.owner_id).respuesta + Owner.find(property.owner_id).amabilidad)/3).round(2)%></p>
								<!-- Button trigger modal -->
								<button type="button" class="btn btn-blue my-1" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
									<i class="bi bi-pencil-fill"></i> Editar Propiedad
								</button>

								<!-- Modal -->
								<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
									<div class="modal-dialog">
										<div class="modal-content">
											<div class="modal-header">
												<h5 class="modal-title" id="staticBackdropLabel">Editar propiedad</h5>
												<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
											</div>
											<div class="modal-body">
												<%= form_for :property, url: property_update_path(property.id) do |f| %>
												<div class="form-group">
													<%= f.label "Dirección" %><br/>
													<%= f.text_field :address, class: "form-control", required: true, value: property.address %>
												</div>
												<div class="form-group">
													<%= f.label "Calificación que le das" %><br/>
													<%= f.select :rating, (1..5).to_a, value: property.rating %>
												</div>
												<div class="form-group">
													<%= f.label "¿Por qué le das esta Calificación?" %><br/>
													<%= f.text_field :description, class: "form-control", required: true, value: property.description %>
												</div>
												<div class="form-group">
													<%= f.label "Url de la imagen" %><br/>
													<%= f.text_field :image, class: "form-control", required: true, value: property.image %>
												</div>
												<div class="form-group">
													<%= f.label "Evidencias (separa cada link por una ,)" %><br/>
													<%= f.text_area :evidence, class: "form-control", required: true, value: property.evidence %>
												</div>
												<div class="form-group">
													<%= f.submit "Editar Propiedad", class: "btn btn-primary mt-3" %>
												</div>

												<% end %>
											</div>
											<div class="modal-footer">
												<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
											</div>
										</div>
									</div>
								</div>
								<%= link_to property_show_path(property.id) do %>
								<div class="btn btn-secondary">
									<i class="bi bi-eye"></i> Ver propiedad
								</div>
								<% end %>
								<%= button_to property_destroy_path(property.id), form: { data: { turbo_confirm: "Estas seguro?" } }, method: :delete, class: "btn btn-danger my-1" do %>
								<i class="bi bi-trash"></i> Borrar propiedad
								<% end %>

							</div>
						</div>
					</div>
					<% end %>
					<% else %>
					<div class="col-12">
						<p class="text-center">Aún no hay propiedades agregadas</p>
					</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/properties/show.html.erb
<section id="property-show" class="container-fluid" style="background-image: url('<%= @property.image %>');">
	<div class="row h-100 align-items-center">
		<div class="col-10 col-sm-9 col-md-8 col-lg-7 col-xl-6 text-center text-white mx-auto">
			<h3> <%= @property.description %> </h3>
			<p> <%= @property.rating %> </p>
		</div>
	</div>
</section>
<section id="property-show-comments" class="container-fluid my-3">
	<!-- Poner el promedio de las calificaciones de rating, security, noise y cleaning y quitar el nombre del dueño -->
	<div class="row">
		<div class="col-10 col-sm-9 col-md-8 col-lg-7 col-xl-6 mx-auto">
			<p class="card-text text-center"><span class="bi bi-shield-shaded"></span> Seguridad: <%= @property.security %></p>
			<p class="card-text text-center"><span class="bi bi-ear"></span> Ruido: <%= @property.noise %></p>
			<p class="card-text text-center"><span class="bi bi-house-heart"></span> Limpieza: <%= @property.cleaning %></p>
			<p class="text-center text-capitalize">Dueño: <%= link_to Faker::Internet.unique.user_name, owner_show_path(@property.owner_id) %></p>
			<p class="text-center text-capitalize">Calificación del dueño: <%=((Owner.find(@property.owner_id).atention + Owner.find(@property.owner_id).respuesta + Owner.find(@property.owner_id).amabilidad)/3).round(2)%></p>
		</div>
	</div>
	<div class="row">
		<div class="col-10 col-sm-9 col-md-8 col-lg-7 col-xl-6 mx-auto">
			<%= link_to "Regresar a las propiedades", properties_index_path, class: "btn btn-primary w-100 my-4" %>
			<div class="container-fluid">
				<div class="row">
					<% if @evidences %>
					<% @evidences.each do |e|%>
					<div class="col-4">
						<img src="<%=e%>" alt="" class="img-fluid">
					</div>
					<%end%>
					<% end %>
				</div>
			</div>
			<h3 class="text-center">
				Lista de comentarios
			</h3>
			<% unless @property.comments.nil? %>
			<% @property.comments.each do |comment|%>
			<div class="rounded shadow radius p-2 m-1">
				<h4><%= User.find(comment.user_id).username %></h4>
				<p><%=comment.content%></p>
				<%comment.rating.times do |t|%>
				<i class="bi bi-star-fill yellow-300"></i>
				<%end%>
				<div class="container">
					<div class="row">
						<% if comment.evidence %>
						<% comment.evidence.split(",").each do |img| %>
						<div class="col-3">
							<img src="<%=img%>" alt="" class="img-fluid">
						</div>
						<% end %>
						<% end %>
					</div>
				</div>
				<a href="mailto:<%= User.find(comment.user_id).email %>" class="btn btn-primary w-100 my-3">Mandar mensaje a este inquilino para resolver dudas</a>
				<%if comment.user_id == current_user.id%>
				<%= button_to 'Borrar comentario', comment_destroy_path(comment.id), form: { data: { turbo_confirm: "Estas seguro?" } }, method: :delete, class: "btn btn-danger my-3 w-100" %>
				<%end%>
			</div>
			<%end%>
			<%end%>

			<div class="rounded shadow radius p-2">
				<%=form_for :comment, url:comment_create_path do |f| %>
				<div class="form-group">
					<%= f.text_field :content, placeholder: "Agrega tu comentario", class: "form-control my-2" %>
				</div>
				<div class="form-group my-3">
					<%=f.label "Calificación"%>
					<%= f.select :rating, (1..5).to_a , class: "form-control" %>
				</div>
				<div class="form-group">
					<%=f.label "Evidencias(Separa cada link por una coma)"%>
					<%= f.text_field :evidence , class: "form-control"%>
				</div>
				<div class="form-group d-none">
					<%= f.text_field :property_id , class: "form-control" , value:@property.id%>
				</div>
				<div class="form-group mt-3">
					<%= f.submit "Comentar", class:"btn btn-primary"%>
				</div>
				<%end%>
			</div>
		</div>
	</div>
</section>

app/views/static_pages/index.html.erb
<section id="hero">
  <div id="heroCarousel" data-bs-interval="5000" class="carousel slide carousel-fade" data-bs-ride="carousel">

    <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

    <div class="carousel-inner" role="listbox">

      <!-- Slide 1 -->
      <% if @properties2 %>
      <% @properties2.each_with_index do |property, index| %>
        <%if index==0%>
        <div class="carousel-item active" id="item<%=index+1%>" style="background-image:url('<%=property.image%>')">
          <%else%>
          <div class="carousel-item" id="item<%=index+1%>" style="background-image:url('<%=property.image%>')">
        <%end%>
          <div class="carousel-container">
            <div class="container w-50">
              <h2 class="animated fadeInDown">¿Interesado en una propiedad?</h2>
              <p class="animated fadeInUp">Mira sus reseñas</p>
              <%= form_with(url: root_path, method: :get, data: {turbo_frame: "porperties"}) do |form| %>
                <%= form.label :query, "Search:", class: "block mb-2 d-flex" %>
                <div class="d-flex space-x-3 ">
                  <%= form.text_field :query, class: "rounded border ring-0 focus:ring-4 focus:ring-orange-100 focus:shadow-none focus:border-orange-500 focus:outline-none form-control" %>
                  <%= form.submit 'Search', class: "btn btn-blue" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
      <% end %>

    </div>

    <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
      <i class="bi bi-chevron-left"></i>
    </a>
    <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
      <i class="bi bi-chevron-right"></i>
    </a>

  </div>
</section><!-- End Hero -->
<section id="home" class="container-fluid">
  <div class="row">
    <div class="col-10 mx-auto py-5">
      <h1 class="text-center">Propiedades</h1>
      <%if current_user%>
      <h4>Hola <%= current_user.username%></h4>
      <%= link_to "Agregar propiedad", properties_index_path, class: "btn btn-blue my-2" %>
      <%end%>
      <div class="container-fluid">
        <%= turbo_frame_tag "properties" do %>
        <div class="row">
          <% if @properties %>    
          <%@properties.each do |property|%>
          <div class="col-12 col-sm-6 col-md-4 col-xl-3">
            <div class="card">
              <img src="<%= property.image %>" class="card-img-top" alt="">
              <div class="card-body">
                <p class="card-text"><p><%= property.description %></p>
                <p class="card-text"><p><%= property.address %></p>

                <% property.rating.to_i.times do |t| %>
                  <span class="fa fa-star"></span>
                <% end %>
                <p class="card-text">Tú calificación: <%= property.rating %></p>
                <p class="card-text"><span class="bi bi-shield-shaded"></span> Seguridad: <%= property.security %></p>
                <p class="card-text"><span class="bi bi-ear"></span> Ruido: <%= property.noise %></p>
                <p class="card-text"><span class="bi bi-house-heart"></span> Limpieza: <%= property.cleaning %></p>
                <p class="text-capitalize">Dueño: <%= link_to Faker::Internet.unique.user_name, owner_show_path(property.owner_id) %></p>
                <p>Calificación del dueño: <%=((Owner.find(property.owner_id).atention + Owner.find(property.owner_id).respuesta + Owner.find(property.owner_id).amabilidad)/3).round(2)%></p>
                <%= link_to property_show_path(property.id) do %>
                <div class="btn btn-secondary">
                  <i class="bi bi-eye"></i> Ver propiedad
                </div>
                <% end %>
              </div>
            </div>
          </div>
          <% end %>
          <% end %>
          
        </div>
        <% end %>
      </div>
    </div>
  </div>
</section>